# -*- mode: ruby -*-
# vi: set ft=ruby :

# Santiago de Cali, March 15th, 2020
# Vagrant file to run a Memcached Server
# OS: UNIX/Linux RedHat CentOS7
# Memcached reference: https://memcached.org/downloads

# Global variables:
SERVICE_NAME = "WMC_MEMCACHED_SERVER"
# SERVICE_PORT = 11211
HOSTNAME = "memcached"
IP_ADDRESS = "192.168.1.235"
OS_NIC_NAME = "eth1"
NETWORK_MASK = "255.255.255.0"
#===========================

#Common dependencies installation scripts:
$script_init = <<SCRIPT
 sudo apt-get upgrade -y
 sudo apt-get update --fix-missing -y
 sudo apt-get install wget -y
 sudo apt-get install nmap -y
 sudo apt-get install vim - y
 sudo apt-get install rpm -y
SCRIPT

#
$script_memcached_installation = <<SCRIPT
 sudo apt-get install memcached -y
 sudo apt-get install libmemcached-tools -y
SCRIPT

# Reference: https://stackoverflow.com/questions/54067192/vagrant-config-vm-provision-does-not-allow-me-to-copy-a-file-to-etc-nginx-conf
$script_memcached_server_configuration = <<SCRIPT
 sudo cp /vagrant/files/memcached.conf /etc/
 sudo cat /etc/memcached.conf
SCRIPT

$script_memcached_run = <<SCRIPT
  sudo netstat -plunt
  sudo service memcached start
  sudo service memcached enable
  sudo service memcached status
SCRIPT
#===========================

Vagrant.configure("2") do |config|

  config.vm.define SERVICE_NAME do |memcached|
    memcached.vm.box = "ubuntu/trusty64"
    memcached.vm.network "public_network", bridge: OS_NIC_NAME, ip:IP_ADDRESS, netmask: NETWORK_MASK
    memcached.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048","--cpus", "2", "--name", SERVICE_NAME]
    end
    # 'RUNNING INIT SCRIPT'
    memcached.vm.provision "shell", inline: $script_init
    # 'RUNNING TO GRANT LOGIN AS ROOT'
    # memcached.vm.provision "shell", path: $script_memcached_root_grant_login
    # 'RUNNING MEMCACHED INSTALLATION SCRIPT'
    memcached.vm.provision "shell", inline: $script_memcached_installation
    # 'RUNNING TO EXECUTE MEMCACHED CONFIGURATION SCRIPTS'
    memcached.vm.provision "shell", inline: $script_memcached_server_configuration
    # 'RUNNING TO EXECUTE MEMCACHED SERVICE SCRIPT'
    memcached.vm.provision "shell", inline: $script_memcached_run

  end

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #config.vm.network "forwarded_port", guest: SERVICE_PORT, host: 8989

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  #config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network" bridge: "enp0s8", ip:"#{$prefijoDireccion+".123"}", netmask: "#{$mascaraRed}"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
